name = "capacity-tracker"
main = "worker/src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "capacity_tracker_db"
database_id = "02445b1c-7502-45ae-9807-a048ce87b7f2"
